// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/acya-skulskaya/yandex-practicum-gophkeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretRepositoryInterface creates a new instance of MockSecretRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepositoryInterface {
	mock := &MockSecretRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretRepositoryInterface is an autogenerated mock type for the SecretRepositoryInterface type
type MockSecretRepositoryInterface struct {
	mock.Mock
}

type MockSecretRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepositoryInterface) EXPECT() *MockSecretRepositoryInterface_Expecter {
	return &MockSecretRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) Create(ctx context.Context, userID uint, name string, secretType string, text string, data []byte) (models.Secret, error) {
	ret := _mock.Called(ctx, userID, name, secretType, text, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string, string, []byte) (models.Secret, error)); ok {
		return returnFunc(ctx, userID, name, secretType, text, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string, string, []byte) models.Secret); ok {
		r0 = returnFunc(ctx, userID, name, secretType, text, data)
	} else {
		r0 = ret.Get(0).(models.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, userID, name, secretType, text, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
//   - secretType string
//   - text string
//   - data []byte
func (_e *MockSecretRepositoryInterface_Expecter) Create(ctx interface{}, userID interface{}, name interface{}, secretType interface{}, text interface{}, data interface{}) *MockSecretRepositoryInterface_Create_Call {
	return &MockSecretRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, secretType, text, data)}
}

func (_c *MockSecretRepositoryInterface_Create_Call) Run(run func(ctx context.Context, userID uint, name string, secretType string, text string, data []byte)) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Create_Call) Return(secret models.Secret, err error) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string, secretType string, text string, data []byte) (models.Secret, error)) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockSecretRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_Delete_Call {
	return &MockSecretRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Delete_Call) Return(err error) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVersion provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) DeleteVersion(ctx context.Context, versionID uint) error {
	ret := _mock.Called(ctx, versionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVersion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, versionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepositoryInterface_DeleteVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVersion'
type MockSecretRepositoryInterface_DeleteVersion_Call struct {
	*mock.Call
}

// DeleteVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - versionID uint
func (_e *MockSecretRepositoryInterface_Expecter) DeleteVersion(ctx interface{}, versionID interface{}) *MockSecretRepositoryInterface_DeleteVersion_Call {
	return &MockSecretRepositoryInterface_DeleteVersion_Call{Call: _e.mock.On("DeleteVersion", ctx, versionID)}
}

func (_c *MockSecretRepositoryInterface_DeleteVersion_Call) Run(run func(ctx context.Context, versionID uint)) *MockSecretRepositoryInterface_DeleteVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_DeleteVersion_Call) Return(err error) *MockSecretRepositoryInterface_DeleteVersion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepositoryInterface_DeleteVersion_Call) RunAndReturn(run func(ctx context.Context, versionID uint) error) *MockSecretRepositoryInterface_DeleteVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) Exists(ctx context.Context, userID uint, id uint) (bool, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSecretRepositoryInterface_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockSecretRepositoryInterface_Expecter) Exists(ctx interface{}, userID interface{}, id interface{}) *MockSecretRepositoryInterface_Exists_Call {
	return &MockSecretRepositoryInterface_Exists_Call{Call: _e.mock.On("Exists", ctx, userID, id)}
}

func (_c *MockSecretRepositoryInterface_Exists_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockSecretRepositoryInterface_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Exists_Call) Return(b bool, err error) *MockSecretRepositoryInterface_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_Exists_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) (bool, error)) *MockSecretRepositoryInterface_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsVersion provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) ExistsVersion(ctx context.Context, versionID uint) (bool, error) {
	ret := _mock.Called(ctx, versionID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsVersion")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return returnFunc(ctx, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = returnFunc(ctx, versionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_ExistsVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsVersion'
type MockSecretRepositoryInterface_ExistsVersion_Call struct {
	*mock.Call
}

// ExistsVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - versionID uint
func (_e *MockSecretRepositoryInterface_Expecter) ExistsVersion(ctx interface{}, versionID interface{}) *MockSecretRepositoryInterface_ExistsVersion_Call {
	return &MockSecretRepositoryInterface_ExistsVersion_Call{Call: _e.mock.On("ExistsVersion", ctx, versionID)}
}

func (_c *MockSecretRepositoryInterface_ExistsVersion_Call) Run(run func(ctx context.Context, versionID uint)) *MockSecretRepositoryInterface_ExistsVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_ExistsVersion_Call) Return(b bool, err error) *MockSecretRepositoryInterface_ExistsVersion_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_ExistsVersion_Call) RunAndReturn(run func(ctx context.Context, versionID uint) (bool, error)) *MockSecretRepositoryInterface_ExistsVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilePath provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) GetFilePath(userID uint, versionID uint) (string, error) {
	ret := _mock.Called(userID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (string, error)); ok {
		return returnFunc(userID, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) string); ok {
		r0 = returnFunc(userID, versionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(userID, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_GetFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilePath'
type MockSecretRepositoryInterface_GetFilePath_Call struct {
	*mock.Call
}

// GetFilePath is a helper method to define mock.On call
//   - userID uint
//   - versionID uint
func (_e *MockSecretRepositoryInterface_Expecter) GetFilePath(userID interface{}, versionID interface{}) *MockSecretRepositoryInterface_GetFilePath_Call {
	return &MockSecretRepositoryInterface_GetFilePath_Call{Call: _e.mock.On("GetFilePath", userID, versionID)}
}

func (_c *MockSecretRepositoryInterface_GetFilePath_Call) Run(run func(userID uint, versionID uint)) *MockSecretRepositoryInterface_GetFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetFilePath_Call) Return(s string, err error) *MockSecretRepositoryInterface_GetFilePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetFilePath_Call) RunAndReturn(run func(userID uint, versionID uint) (string, error)) *MockSecretRepositoryInterface_GetFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersionID provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) GetLatestVersionID(ctx context.Context, id uint) (uint, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersionID")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (uint, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) uint); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_GetLatestVersionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersionID'
type MockSecretRepositoryInterface_GetLatestVersionID_Call struct {
	*mock.Call
}

// GetLatestVersionID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockSecretRepositoryInterface_Expecter) GetLatestVersionID(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_GetLatestVersionID_Call {
	return &MockSecretRepositoryInterface_GetLatestVersionID_Call{Call: _e.mock.On("GetLatestVersionID", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_GetLatestVersionID_Call) Run(run func(ctx context.Context, id uint)) *MockSecretRepositoryInterface_GetLatestVersionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetLatestVersionID_Call) Return(v uint, err error) *MockSecretRepositoryInterface_GetLatestVersionID_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetLatestVersionID_Call) RunAndReturn(run func(ctx context.Context, id uint) (uint, error)) *MockSecretRepositoryInterface_GetLatestVersionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithVersion provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) GetWithVersion(ctx context.Context, userID uint, id uint, versionID uint) (models.Secret, error) {
	ret := _mock.Called(ctx, userID, id, versionID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithVersion")
	}

	var r0 models.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) (models.Secret, error)); ok {
		return returnFunc(ctx, userID, id, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) models.Secret); ok {
		r0 = returnFunc(ctx, userID, id, versionID)
	} else {
		r0 = ret.Get(0).(models.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, id, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_GetWithVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithVersion'
type MockSecretRepositoryInterface_GetWithVersion_Call struct {
	*mock.Call
}

// GetWithVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - versionID uint
func (_e *MockSecretRepositoryInterface_Expecter) GetWithVersion(ctx interface{}, userID interface{}, id interface{}, versionID interface{}) *MockSecretRepositoryInterface_GetWithVersion_Call {
	return &MockSecretRepositoryInterface_GetWithVersion_Call{Call: _e.mock.On("GetWithVersion", ctx, userID, id, versionID)}
}

func (_c *MockSecretRepositoryInterface_GetWithVersion_Call) Run(run func(ctx context.Context, userID uint, id uint, versionID uint)) *MockSecretRepositoryInterface_GetWithVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetWithVersion_Call) Return(secret models.Secret, err error) *MockSecretRepositoryInterface_GetWithVersion_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetWithVersion_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, versionID uint) (models.Secret, error)) *MockSecretRepositoryInterface_GetWithVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithVersionsList provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) GetWithVersionsList(ctx context.Context, userID uint, id uint) (models.Secret, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWithVersionsList")
	}

	var r0 models.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (models.Secret, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) models.Secret); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(models.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_GetWithVersionsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithVersionsList'
type MockSecretRepositoryInterface_GetWithVersionsList_Call struct {
	*mock.Call
}

// GetWithVersionsList is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockSecretRepositoryInterface_Expecter) GetWithVersionsList(ctx interface{}, userID interface{}, id interface{}) *MockSecretRepositoryInterface_GetWithVersionsList_Call {
	return &MockSecretRepositoryInterface_GetWithVersionsList_Call{Call: _e.mock.On("GetWithVersionsList", ctx, userID, id)}
}

func (_c *MockSecretRepositoryInterface_GetWithVersionsList_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockSecretRepositoryInterface_GetWithVersionsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetWithVersionsList_Call) Return(secret models.Secret, err error) *MockSecretRepositoryInterface_GetWithVersionsList_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetWithVersionsList_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) (models.Secret, error)) *MockSecretRepositoryInterface_GetWithVersionsList_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) List(ctx context.Context, userID uint) ([]models.Secret, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]models.Secret, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []models.Secret); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecretRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSecretRepositoryInterface_Expecter) List(ctx interface{}, userID interface{}) *MockSecretRepositoryInterface_List_Call {
	return &MockSecretRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockSecretRepositoryInterface_List_Call) Run(run func(ctx context.Context, userID uint)) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_List_Call) Return(secrets []models.Secret, err error) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_List_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]models.Secret, error)) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBinary provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) SaveBinary(ctx context.Context, userID uint, secretVersionID uint, data []byte) error {
	ret := _mock.Called(ctx, userID, secretVersionID, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveBinary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, []byte) error); ok {
		r0 = returnFunc(ctx, userID, secretVersionID, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepositoryInterface_SaveBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBinary'
type MockSecretRepositoryInterface_SaveBinary_Call struct {
	*mock.Call
}

// SaveBinary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - secretVersionID uint
//   - data []byte
func (_e *MockSecretRepositoryInterface_Expecter) SaveBinary(ctx interface{}, userID interface{}, secretVersionID interface{}, data interface{}) *MockSecretRepositoryInterface_SaveBinary_Call {
	return &MockSecretRepositoryInterface_SaveBinary_Call{Call: _e.mock.On("SaveBinary", ctx, userID, secretVersionID, data)}
}

func (_c *MockSecretRepositoryInterface_SaveBinary_Call) Run(run func(ctx context.Context, userID uint, secretVersionID uint, data []byte)) *MockSecretRepositoryInterface_SaveBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_SaveBinary_Call) Return(err error) *MockSecretRepositoryInterface_SaveBinary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepositoryInterface_SaveBinary_Call) RunAndReturn(run func(ctx context.Context, userID uint, secretVersionID uint, data []byte) error) *MockSecretRepositoryInterface_SaveBinary_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) Update(ctx context.Context, userID uint, id uint, name string, text string, data []byte) (models.Secret, error) {
	ret := _mock.Called(ctx, userID, id, name, text, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string, []byte) (models.Secret, error)); ok {
		return returnFunc(ctx, userID, id, name, text, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string, []byte) models.Secret); ok {
		r0 = returnFunc(ctx, userID, id, name, text, data)
	} else {
		r0 = ret.Get(0).(models.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, userID, id, name, text, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSecretRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - name string
//   - text string
//   - data []byte
func (_e *MockSecretRepositoryInterface_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, name interface{}, text interface{}, data interface{}) *MockSecretRepositoryInterface_Update_Call {
	return &MockSecretRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, name, text, data)}
}

func (_c *MockSecretRepositoryInterface_Update_Call) Run(run func(ctx context.Context, userID uint, id uint, name string, text string, data []byte)) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Update_Call) Return(secret models.Secret, err error) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, name string, text string, data []byte) (models.Secret, error)) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// VersionsCount provides a mock function for the type MockSecretRepositoryInterface
func (_mock *MockSecretRepositoryInterface) VersionsCount(ctx context.Context, id uint) (uint, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VersionsCount")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (uint, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) uint); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepositoryInterface_VersionsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionsCount'
type MockSecretRepositoryInterface_VersionsCount_Call struct {
	*mock.Call
}

// VersionsCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockSecretRepositoryInterface_Expecter) VersionsCount(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_VersionsCount_Call {
	return &MockSecretRepositoryInterface_VersionsCount_Call{Call: _e.mock.On("VersionsCount", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_VersionsCount_Call) Run(run func(ctx context.Context, id uint)) *MockSecretRepositoryInterface_VersionsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_VersionsCount_Call) Return(v uint, err error) *MockSecretRepositoryInterface_VersionsCount_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSecretRepositoryInterface_VersionsCount_Call) RunAndReturn(run func(ctx context.Context, id uint) (uint, error)) *MockSecretRepositoryInterface_VersionsCount_Call {
	_c.Call.Return(run)
	return _c
}
