// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/acya-skulskaya/yandex-practicum-gophkeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Create(ctx context.Context, login string, password string) (models.User, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (models.User, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) models.User); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockUserRepositoryInterface_Expecter) Create(ctx interface{}, login interface{}, password interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, login, password)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(ctx context.Context, login string, password string)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(user models.User, err error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (models.User, error)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Get(ctx context.Context, id any) (models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserRepositoryInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id any
func (_e *MockUserRepositoryInterface_Expecter) Get(ctx interface{}, id interface{}) *MockUserRepositoryInterface_Get_Call {
	return &MockUserRepositoryInterface_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUserRepositoryInterface_Get_Call) Run(run func(ctx context.Context, id any)) *MockUserRepositoryInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Get_Call) Return(user models.User, err error) *MockUserRepositoryInterface_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_Get_Call) RunAndReturn(run func(ctx context.Context, id any) (models.User, error)) *MockUserRepositoryInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}
