edition = "2023";

package acyaskulskaya.gophkeeper.secret;

option go_package = "github.com/acya-skulskaya/yandex-practicum-gophkeeper/api/gophkeeper/";

import "google/protobuf/timestamp.proto";

// SecretService handles manipulations with user's secrets
service SecretService {
  // Allows to add a new secret to storage
  rpc Store (SecretStoreRequest) returns (SecretResponse);
  // Allows to update a secret's name or/and it's data
  rpc Update (SecretUpdateRequest) returns (SecretResponse);
  // Will return secret's data (if it's not of type binary) for a specified version or a list of versions. If version ID is 0, will return data for the latest version
  rpc Show (SecretShowRequest) returns (SecretResponse);
  // Allows to download secret's data if it's of type binary
  rpc Download (SecretShowRequest) returns (SecretDataResponse);
  // Will return a list of all secrets for authorized user with a list of all versions
  rpc Sync (SyncRequest) returns (SyncResponse);
  // Will delete a secret or a version of a secret, if version ID was specified
  rpc Delete (SecretDeleteRequest) returns (SecretDeleteResponse);
}

// Field types
message SecretData {
  string text = 1;
  bytes data = 2;
}
message SecretVersion {
  string version_id = 1;
  google.protobuf.Timestamp created_at = 2;
  SecretData data = 3;
}
enum SecretType {
  SECRET_TYPE_UNSPECIFIED = 0;
  SECRET_TYPE_LOGIN_PASSWORD = 1;
  SECRET_TYPE_TEXT = 2;
  SECRET_TYPE_BANK_CARD = 3;
  SECRET_TYPE_BINARY = 4;
}

// Requests
message SecretStoreRequest {
  reserved 1;
  SecretType type = 2;
  string name = 3;
  SecretData data = 4;
}
message SecretUpdateRequest {
  reserved 1;
  string id = 2;
  string name = 3;
  SecretData data = 4;
}
message SecretShowRequest {
  reserved 1;
  string id = 2;
  string version_id = 3;
}
message SyncRequest {
  reserved 1;
  // Type type = 2; - no need for this functionality now, unimplemented
}
message SecretDeleteRequest {
  reserved 1;
  string id = 2;
  string version_id = 3;
}

// Responses
message SecretResponse {
  string id = 1;
  SecretType type = 2;
  string name = 3;
  string version_id = 4;
  SecretData data = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  repeated SecretVersion versions = 8;
}
message SecretDataResponse {
  SecretType type = 1;
  string version_id = 2;
  SecretData data = 3;
  google.protobuf.Timestamp created_at = 4;
}
message SyncResponse {
  repeated SecretResponse secrets = 1;
}
message SecretDeleteResponse {
  // empty for now
}
