// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/gophkeeper/secret.proto

package gophkeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// SkipVerify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// SkipVerify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 1
	SecretType_SECRET_TYPE_TEXT           SecretType = 2
	SecretType_SECRET_TYPE_BANK_CARD      SecretType = 3
	SecretType_SECRET_TYPE_BINARY         SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_LOGIN_PASSWORD",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BANK_CARD",
		4: "SECRET_TYPE_BINARY",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_LOGIN_PASSWORD": 1,
		"SECRET_TYPE_TEXT":           2,
		"SECRET_TYPE_BANK_CARD":      3,
		"SECRET_TYPE_BINARY":         4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gophkeeper_secret_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_api_gophkeeper_secret_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Field types
type SecretData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text        *string                `protobuf:"bytes,1,opt,name=text"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretData) Reset() {
	*x = SecretData{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretData) ProtoMessage() {}

func (x *SecretData) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretData) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *SecretData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretData) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SecretData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SecretData) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretData) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Text = nil
}

func (x *SecretData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type SecretData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text *string
	Data []byte
}

func (b0 SecretData_builder) Build() *SecretData {
	m0 := &SecretData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Text = b.Text
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type SecretVersion struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VersionId   *string                `protobuf:"bytes,1,opt,name=version_id,json=versionId"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt"`
	xxx_hidden_Data        *SecretData            `protobuf:"bytes,3,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretVersion) Reset() {
	*x = SecretVersion{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVersion) ProtoMessage() {}

func (x *SecretVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretVersion) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *SecretVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SecretVersion) GetData() *SecretData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretVersion) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SecretVersion) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretVersion) SetData(v *SecretData) {
	x.xxx_hidden_Data = v
}

func (x *SecretVersion) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretVersion) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SecretVersion) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *SecretVersion) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_VersionId = nil
}

func (x *SecretVersion) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *SecretVersion) ClearData() {
	x.xxx_hidden_Data = nil
}

type SecretVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VersionId *string
	CreatedAt *timestamppb.Timestamp
	Data      *SecretData
}

func (b0 SecretVersion_builder) Build() *SecretVersion {
	m0 := &SecretVersion{}
	b, x := &b0, m0
	_, _ = b, x
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_VersionId = b.VersionId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Data = b.Data
	return m0
}

// Requests
type SecretStoreRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        SecretType             `protobuf:"varint,2,opt,name=type,enum=acyaskulskaya.gophkeeper.secret.SecretType"`
	xxx_hidden_Name        *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Data        *SecretData            `protobuf:"bytes,4,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretStoreRequest) Reset() {
	*x = SecretStoreRequest{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretStoreRequest) ProtoMessage() {}

func (x *SecretStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretStoreRequest) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretStoreRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SecretStoreRequest) GetData() *SecretData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretStoreRequest) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SecretStoreRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SecretStoreRequest) SetData(v *SecretData) {
	x.xxx_hidden_Data = v
}

func (x *SecretStoreRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretStoreRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretStoreRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *SecretStoreRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretStoreRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *SecretStoreRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type SecretStoreRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type *SecretType
	Name *string
	Data *SecretData
}

func (b0 SecretStoreRequest_builder) Build() *SecretStoreRequest {
	m0 := &SecretStoreRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

type SecretUpdateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Data        *SecretData            `protobuf:"bytes,4,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretUpdateRequest) Reset() {
	*x = SecretUpdateRequest{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretUpdateRequest) ProtoMessage() {}

func (x *SecretUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretUpdateRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SecretUpdateRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SecretUpdateRequest) GetData() *SecretData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretUpdateRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SecretUpdateRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SecretUpdateRequest) SetData(v *SecretData) {
	x.xxx_hidden_Data = v
}

func (x *SecretUpdateRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretUpdateRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretUpdateRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *SecretUpdateRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *SecretUpdateRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *SecretUpdateRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type SecretUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *string
	Name *string
	Data *SecretData
}

func (b0 SecretUpdateRequest_builder) Build() *SecretUpdateRequest {
	m0 := &SecretUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

type SecretShowRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_VersionId   *string                `protobuf:"bytes,3,opt,name=version_id,json=versionId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretShowRequest) Reset() {
	*x = SecretShowRequest{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretShowRequest) ProtoMessage() {}

func (x *SecretShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretShowRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SecretShowRequest) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *SecretShowRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SecretShowRequest) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SecretShowRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretShowRequest) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretShowRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *SecretShowRequest) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_VersionId = nil
}

type SecretShowRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	VersionId *string
}

func (b0 SecretShowRequest_builder) Build() *SecretShowRequest {
	m0 := &SecretShowRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_VersionId = b.VersionId
	}
	return m0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SyncRequest_builder) Build() *SyncRequest {
	m0 := &SyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SecretDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_VersionId   *string                `protobuf:"bytes,3,opt,name=version_id,json=versionId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretDeleteRequest) Reset() {
	*x = SecretDeleteRequest{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteRequest) ProtoMessage() {}

func (x *SecretDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretDeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SecretDeleteRequest) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *SecretDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SecretDeleteRequest) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SecretDeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretDeleteRequest) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretDeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *SecretDeleteRequest) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_VersionId = nil
}

type SecretDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	VersionId *string
}

func (b0 SecretDeleteRequest_builder) Build() *SecretDeleteRequest {
	m0 := &SecretDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_VersionId = b.VersionId
	}
	return m0
}

// Responses
type SecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type        SecretType             `protobuf:"varint,2,opt,name=type,enum=acyaskulskaya.gophkeeper.secret.SecretType"`
	xxx_hidden_Name        *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_VersionId   *string                `protobuf:"bytes,4,opt,name=version_id,json=versionId"`
	xxx_hidden_Data        *SecretData            `protobuf:"bytes,5,opt,name=data"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_Versions    *[]*SecretVersion      `protobuf:"bytes,8,rep,name=versions"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretResponse) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) GetData() *SecretData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SecretResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *SecretResponse) GetVersions() []*SecretVersion {
	if x != nil {
		if x.xxx_hidden_Versions != nil {
			return *x.xxx_hidden_Versions
		}
	}
	return nil
}

func (x *SecretResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *SecretResponse) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *SecretResponse) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *SecretResponse) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *SecretResponse) SetData(v *SecretData) {
	x.xxx_hidden_Data = v
}

func (x *SecretResponse) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretResponse) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *SecretResponse) SetVersions(v []*SecretVersion) {
	x.xxx_hidden_Versions = &v
}

func (x *SecretResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretResponse) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretResponse) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SecretResponse) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SecretResponse) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *SecretResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SecretResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *SecretResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *SecretResponse) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretResponse) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *SecretResponse) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_VersionId = nil
}

func (x *SecretResponse) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *SecretResponse) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *SecretResponse) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type SecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Type      *SecretType
	Name      *string
	VersionId *string
	Data      *SecretData
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
	Versions  []*SecretVersion
}

func (b0 SecretResponse_builder) Build() *SecretResponse {
	m0 := &SecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_VersionId = b.VersionId
	}
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_Versions = &b.Versions
	return m0
}

type SecretDataResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        SecretType             `protobuf:"varint,1,opt,name=type,enum=acyaskulskaya.gophkeeper.secret.SecretType"`
	xxx_hidden_VersionId   *string                `protobuf:"bytes,2,opt,name=version_id,json=versionId"`
	xxx_hidden_Data        *SecretData            `protobuf:"bytes,3,opt,name=data"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretDataResponse) Reset() {
	*x = SecretDataResponse{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDataResponse) ProtoMessage() {}

func (x *SecretDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretDataResponse) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretDataResponse) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *SecretDataResponse) GetData() *SecretData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *SecretDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SecretDataResponse) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SecretDataResponse) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SecretDataResponse) SetData(v *SecretData) {
	x.xxx_hidden_Data = v
}

func (x *SecretDataResponse) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretDataResponse) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretDataResponse) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretDataResponse) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *SecretDataResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SecretDataResponse) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretDataResponse) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_VersionId = nil
}

func (x *SecretDataResponse) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *SecretDataResponse) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type SecretDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      *SecretType
	VersionId *string
	Data      *SecretData
	CreatedAt *timestamppb.Timestamp
}

func (b0 SecretDataResponse_builder) Build() *SecretDataResponse {
	m0 := &SecretDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_VersionId = b.VersionId
	}
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type SyncResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*SecretResponse     `protobuf:"bytes,1,rep,name=secrets"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncResponse) GetSecrets() []*SecretResponse {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *SyncResponse) SetSecrets(v []*SecretResponse) {
	x.xxx_hidden_Secrets = &v
}

type SyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*SecretResponse
}

func (b0 SyncResponse_builder) Build() *SyncResponse {
	m0 := &SyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

type SecretDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteResponse) Reset() {
	*x = SecretDeleteResponse{}
	mi := &file_api_gophkeeper_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteResponse) ProtoMessage() {}

func (x *SecretDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SecretDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SecretDeleteResponse_builder) Build() *SecretDeleteResponse {
	m0 := &SecretDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_gophkeeper_secret_proto protoreflect.FileDescriptor

const file_api_gophkeeper_secret_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/gophkeeper/secret.proto\x12\x1facyaskulskaya.gophkeeper.secret\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\n" +
	"SecretData\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xaa\x01\n" +
	"\rSecretVersion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\x04data\x18\x03 \x01(\v2+.acyaskulskaya.gophkeeper.secret.SecretDataR\x04data\"\xb0\x01\n" +
	"\x12SecretStoreRequest\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.acyaskulskaya.gophkeeper.secret.SecretTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12?\n" +
	"\x04data\x18\x04 \x01(\v2+.acyaskulskaya.gophkeeper.secret.SecretDataR\x04dataJ\x04\b\x01\x10\x02\"\x80\x01\n" +
	"\x13SecretUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12?\n" +
	"\x04data\x18\x04 \x01(\v2+.acyaskulskaya.gophkeeper.secret.SecretDataR\x04dataJ\x04\b\x01\x10\x02\"H\n" +
	"\x11SecretShowRequest\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionIdJ\x04\b\x01\x10\x02\"\x13\n" +
	"\vSyncRequestJ\x04\b\x01\x10\x02\"J\n" +
	"\x13SecretDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionIdJ\x04\b\x01\x10\x02\"\x97\x03\n" +
	"\x0eSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.acyaskulskaya.gophkeeper.secret.SecretTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12?\n" +
	"\x04data\x18\x05 \x01(\v2+.acyaskulskaya.gophkeeper.secret.SecretDataR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12J\n" +
	"\bversions\x18\b \x03(\v2..acyaskulskaya.gophkeeper.secret.SecretVersionR\bversions\"\xf0\x01\n" +
	"\x12SecretDataResponse\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.acyaskulskaya.gophkeeper.secret.SecretTypeR\x04type\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12?\n" +
	"\x04data\x18\x03 \x01(\v2+.acyaskulskaya.gophkeeper.secret.SecretDataR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Y\n" +
	"\fSyncResponse\x12I\n" +
	"\asecrets\x18\x01 \x03(\v2/.acyaskulskaya.gophkeeper.secret.SecretResponseR\asecrets\"\x16\n" +
	"\x14SecretDeleteResponse*\x92\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x19\n" +
	"\x15SECRET_TYPE_BANK_CARD\x10\x03\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x042\xad\x05\n" +
	"\rSecretService\x12m\n" +
	"\x05Store\x123.acyaskulskaya.gophkeeper.secret.SecretStoreRequest\x1a/.acyaskulskaya.gophkeeper.secret.SecretResponse\x12o\n" +
	"\x06Update\x124.acyaskulskaya.gophkeeper.secret.SecretUpdateRequest\x1a/.acyaskulskaya.gophkeeper.secret.SecretResponse\x12k\n" +
	"\x04Show\x122.acyaskulskaya.gophkeeper.secret.SecretShowRequest\x1a/.acyaskulskaya.gophkeeper.secret.SecretResponse\x12s\n" +
	"\bDownload\x122.acyaskulskaya.gophkeeper.secret.SecretShowRequest\x1a3.acyaskulskaya.gophkeeper.secret.SecretDataResponse\x12c\n" +
	"\x04Sync\x12,.acyaskulskaya.gophkeeper.secret.SyncRequest\x1a-.acyaskulskaya.gophkeeper.secret.SyncResponse\x12u\n" +
	"\x06Delete\x124.acyaskulskaya.gophkeeper.secret.SecretDeleteRequest\x1a5.acyaskulskaya.gophkeeper.secret.SecretDeleteResponseBGZEgithub.com/acya-skulskaya/yandex-practicum-gophkeeper/api/gophkeeper/b\beditionsp\xe8\a"

var file_api_gophkeeper_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gophkeeper_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_gophkeeper_secret_proto_goTypes = []any{
	(SecretType)(0),               // 0: acyaskulskaya.gophkeeper.secret.SecretType
	(*SecretData)(nil),            // 1: acyaskulskaya.gophkeeper.secret.SecretData
	(*SecretVersion)(nil),         // 2: acyaskulskaya.gophkeeper.secret.SecretVersion
	(*SecretStoreRequest)(nil),    // 3: acyaskulskaya.gophkeeper.secret.SecretStoreRequest
	(*SecretUpdateRequest)(nil),   // 4: acyaskulskaya.gophkeeper.secret.SecretUpdateRequest
	(*SecretShowRequest)(nil),     // 5: acyaskulskaya.gophkeeper.secret.SecretShowRequest
	(*SyncRequest)(nil),           // 6: acyaskulskaya.gophkeeper.secret.SyncRequest
	(*SecretDeleteRequest)(nil),   // 7: acyaskulskaya.gophkeeper.secret.SecretDeleteRequest
	(*SecretResponse)(nil),        // 8: acyaskulskaya.gophkeeper.secret.SecretResponse
	(*SecretDataResponse)(nil),    // 9: acyaskulskaya.gophkeeper.secret.SecretDataResponse
	(*SyncResponse)(nil),          // 10: acyaskulskaya.gophkeeper.secret.SyncResponse
	(*SecretDeleteResponse)(nil),  // 11: acyaskulskaya.gophkeeper.secret.SecretDeleteResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_api_gophkeeper_secret_proto_depIdxs = []int32{
	12, // 0: acyaskulskaya.gophkeeper.secret.SecretVersion.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: acyaskulskaya.gophkeeper.secret.SecretVersion.data:type_name -> acyaskulskaya.gophkeeper.secret.SecretData
	0,  // 2: acyaskulskaya.gophkeeper.secret.SecretStoreRequest.type:type_name -> acyaskulskaya.gophkeeper.secret.SecretType
	1,  // 3: acyaskulskaya.gophkeeper.secret.SecretStoreRequest.data:type_name -> acyaskulskaya.gophkeeper.secret.SecretData
	1,  // 4: acyaskulskaya.gophkeeper.secret.SecretUpdateRequest.data:type_name -> acyaskulskaya.gophkeeper.secret.SecretData
	0,  // 5: acyaskulskaya.gophkeeper.secret.SecretResponse.type:type_name -> acyaskulskaya.gophkeeper.secret.SecretType
	1,  // 6: acyaskulskaya.gophkeeper.secret.SecretResponse.data:type_name -> acyaskulskaya.gophkeeper.secret.SecretData
	12, // 7: acyaskulskaya.gophkeeper.secret.SecretResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 8: acyaskulskaya.gophkeeper.secret.SecretResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 9: acyaskulskaya.gophkeeper.secret.SecretResponse.versions:type_name -> acyaskulskaya.gophkeeper.secret.SecretVersion
	0,  // 10: acyaskulskaya.gophkeeper.secret.SecretDataResponse.type:type_name -> acyaskulskaya.gophkeeper.secret.SecretType
	1,  // 11: acyaskulskaya.gophkeeper.secret.SecretDataResponse.data:type_name -> acyaskulskaya.gophkeeper.secret.SecretData
	12, // 12: acyaskulskaya.gophkeeper.secret.SecretDataResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 13: acyaskulskaya.gophkeeper.secret.SyncResponse.secrets:type_name -> acyaskulskaya.gophkeeper.secret.SecretResponse
	3,  // 14: acyaskulskaya.gophkeeper.secret.SecretService.Store:input_type -> acyaskulskaya.gophkeeper.secret.SecretStoreRequest
	4,  // 15: acyaskulskaya.gophkeeper.secret.SecretService.Update:input_type -> acyaskulskaya.gophkeeper.secret.SecretUpdateRequest
	5,  // 16: acyaskulskaya.gophkeeper.secret.SecretService.Show:input_type -> acyaskulskaya.gophkeeper.secret.SecretShowRequest
	5,  // 17: acyaskulskaya.gophkeeper.secret.SecretService.Download:input_type -> acyaskulskaya.gophkeeper.secret.SecretShowRequest
	6,  // 18: acyaskulskaya.gophkeeper.secret.SecretService.Sync:input_type -> acyaskulskaya.gophkeeper.secret.SyncRequest
	7,  // 19: acyaskulskaya.gophkeeper.secret.SecretService.Delete:input_type -> acyaskulskaya.gophkeeper.secret.SecretDeleteRequest
	8,  // 20: acyaskulskaya.gophkeeper.secret.SecretService.Store:output_type -> acyaskulskaya.gophkeeper.secret.SecretResponse
	8,  // 21: acyaskulskaya.gophkeeper.secret.SecretService.Update:output_type -> acyaskulskaya.gophkeeper.secret.SecretResponse
	8,  // 22: acyaskulskaya.gophkeeper.secret.SecretService.Show:output_type -> acyaskulskaya.gophkeeper.secret.SecretResponse
	9,  // 23: acyaskulskaya.gophkeeper.secret.SecretService.Download:output_type -> acyaskulskaya.gophkeeper.secret.SecretDataResponse
	10, // 24: acyaskulskaya.gophkeeper.secret.SecretService.Sync:output_type -> acyaskulskaya.gophkeeper.secret.SyncResponse
	11, // 25: acyaskulskaya.gophkeeper.secret.SecretService.Delete:output_type -> acyaskulskaya.gophkeeper.secret.SecretDeleteResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_gophkeeper_secret_proto_init() }
func file_api_gophkeeper_secret_proto_init() {
	if File_api_gophkeeper_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gophkeeper_secret_proto_rawDesc), len(file_api_gophkeeper_secret_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gophkeeper_secret_proto_goTypes,
		DependencyIndexes: file_api_gophkeeper_secret_proto_depIdxs,
		EnumInfos:         file_api_gophkeeper_secret_proto_enumTypes,
		MessageInfos:      file_api_gophkeeper_secret_proto_msgTypes,
	}.Build()
	File_api_gophkeeper_secret_proto = out.File
	file_api_gophkeeper_secret_proto_goTypes = nil
	file_api_gophkeeper_secret_proto_depIdxs = nil
}
